Make language actually working
wiremod/advduplicator pull request #85
Opened 2020-09-06 12:24 UTC by Blueberryy

2020-09-06 20:50 UTC, TomyLobo requested changes

2020-09-06 20:50 UTC, TomyLobo commented on resource/localization/en/adv_dublicator_tool.properties
> +
the file name is misspelled, please correct

2020-09-06 20:50 UTC, TomyLobo commented on resource/localization/ru/adv_dublicator_tool.properties
> +
the file name is misspelled, please correct

2020-09-06 21:41 UTC, Blueberryy commented
ah sorry, will fix soon

2020-09-08 05:04 UTC, Blueberryy commented
fixed

2020-09-08 11:09 UTC, thegrb93 commented
I think we'll need a resource.AddWorkshop for this now so the new files get acquired.

2020-09-08 16:00 UTC, Blueberryy commented
Files downloading if you subbed to addon, i don't think we actually need to add this

2020-09-08 16:22 UTC, thegrb93 commented
What if we instead do
```lua
if GetConvarString("whatever_language_convar_is")=="ru" then
    language.Add("...","russian")
else
    language.Add("...","english")
end
```

2020-09-08 19:47 UTC, thegrb93 commented
It does

2020-09-09 13:16 UTC, thegrb93 requested changes
Use `GetConvarString("gmod_language")` instead of .properties files.

2020-09-12 10:20 UTC, closed without merging